### ISSUE TITLE
Todos in Branch other than the Default Branch?

### ISSUE THREAD

**Issue by JanaJarecki** [JasonEtco/todo#257]
**Is your feature request related to a problem? Please describe.**
Hi, I very much love this app, thank you! A feature I am missing is to allow todos from any branch,.

**Describe the solution you'd like**
A simple option like anybranch = true would do it.

**Describe alternatives you've considered**
None really, I don't know if this is technically difficult for you guys :)

**Additional context**
None.

Cheers,
Jana

**Comment by JasonEtco** [comment]
Hello! Thanks for the kind words ❤️ The current behavior for non-master branches is to post comments in a pull request - so if the branch has an open PR, the TODOs will be posted there, and created as issues when the PR is merged. Does that work for your use-case?

If not, I think that providing a list of branches, or a RegEx (including a `*` option), would be a nice addition. Something like:

```yaml
todo:
  # Specific branches
  branches:
    - master
    - dev
   
  # Any branch
  branches: *

  # RegEx
  branches: dev/*
```
