### ISSUE TITLE
Custom labels for keywords

### ISSUE THREAD

**Issue by FilipMalczak** [JasonEtco/todo#262]
All the issues created with `todo` bot are only tagged with `todo` or can have fixed set of labels. It's hard to recognize which issue relates to `todo`, `fixme`, `techdebt`, etc.

I'd like to have additional config field that would be an object (map, key-value set) that maps keywords to label sets.

E.g (`labelMapping` is an example, I don't think that's the best name for that field).

```
keyword: [ "todo", "fixme", "techdebt" ]
labelMapping: 
  todo: "enhancement"
  fixme: ["bug", "help wanted"]
  techdebt: true
```

`keyword` field could be skipped and keyword set could be recognized from the mapping keys, but for convention-over-configuration sake I'd leave it.

In given example occurence of `techdebt` would result in `techdebt` label. It is aligned with current labels field behaviour.
